# Generated by Django 3.2.12 on 2023-08-02 11:45

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_agent_image_path),
        ),
    ]
