# Generated by Django 3.2.12 on 2023-08-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230803_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentfeedback',
            name='slogan',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
