# Generated by Django 3.2.12 on 2023-08-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230804_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='slogan',
            field=models.CharField(blank=True, default='Нет девиза', max_length=300),
        ),
    ]
