# Generated by Django 3.2.12 on 2023-08-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0011_alter_category_image'),
        ('users', '0007_alter_agent_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='districts',
            field=models.ManyToManyField(blank=True, to='objects.District'),
        ),
    ]
