# Generated by Django 3.2.12 on 2023-07-30 15:24

from django.db import migrations, models
import django.db.models.deletion
import objects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationToView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], default='sale', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('current_floor', models.IntegerField(blank=True, null=True)),
                ('total_floors', models.IntegerField(blank=True, null=True)),
                ('otoplenie', models.CharField(blank=True, max_length=50, null=True)),
                ('remont', models.CharField(blank=True, max_length=50, null=True)),
                ('furniture', models.CharField(blank=True, max_length=50, null=True)),
                ('window_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.IntegerField()),
                ('type', models.CharField(choices=[('flat', 'Квартира'), ('house', 'Дом'), ('plot', 'Участок'), ('office', 'Офис')], default='flat', max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('year_built', models.IntegerField(blank=True, default=2010, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ad_type', models.CharField(choices=[('rent', 'Аренда'), ('sale', 'Продажа')], default='sale', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=objects.models.get_image_path)),
                ('object_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='objects.objectad')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('object_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='objects.objectad')),
            ],
        ),
    ]
