# Generated by Django 3.2.12 on 2023-07-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoview',
            name='type',
            field=models.CharField(choices=[('buy', 'Купить'), ('sell', 'Продать')], default='sale', max_length=20),
        ),
    ]
