# Generated by Django 3.2.12 on 2023-08-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectad',
            name='description',
        ),
    ]
