# Generated by Django 3.2.12 on 2023-08-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_objectad_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectad',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='objectad',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
