# Generated by Django 3.2.12 on 2023-08-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_auto_20230808_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectad',
            old_name='company_name',
            new_name='balcony',
        ),
        migrations.RemoveField(
            model_name='objectad',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='objectad',
            name='remont',
        ),
        migrations.RemoveField(
            model_name='objectad',
            name='year_built',
        ),
        migrations.AddField(
            model_name='objectad',
            name='kitchens_area',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectad',
            name='security',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='objectad',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'Завершен'), ('incomplete', 'Не завершен')], default='completed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='objectad',
            name='zastroishik',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectad',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
