# Generated by Django 3.2.12 on 2023-08-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20230809_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectad',
            name='documents',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
