# Generated by Django 3.2.12 on 2023-08-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_objectad_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectad',
            name='walls_material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
