# Generated by Django 3.2.12 on 2023-08-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_objectad_walls_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectad',
            name='ad_type',
            field=models.CharField(choices=[('Аренда', 'Аренда'), ('Продажа', 'Продажа')], default='Продажа', max_length=10),
        ),
    ]
