# Generated by Django 3.2.12 on 2023-08-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_alter_objectad_ad_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectad',
            name='kitchens_area',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
