# Generated by Django 3.2.12 on 2023-08-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_alter_objectad_kitchens_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
